/**
 * Generates supabase/seed.sql from the same TypeScript catalogue data the
 * app used to seed AsyncStorage with. This keeps the database's built-in
 * exercise library and programme catalogue mechanically in sync with
 * data/seedExercises.ts and data/programmeCatalogue.ts — the source of
 * truth for their *content* stays one authored TypeScript file per concern,
 * exactly as before; only *where it's loaded into* has moved.
 *
 * Run with: npx tsx scripts/generateSeedSql.ts
 * (from apps/mobile — re-run any time the catalogue or exercise library changes,
 * then re-apply with `supabase db reset` locally or `supabase db push` remotely.)
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { SEED_EXERCISES } from "../data/seedExercises";
import { SEED_PROGRAM_EXERCISES, SEED_PROGRAMS, SEED_WORKOUT_DAYS } from "../data/programmeCatalogue";
import { exerciseToRow } from "../lib/repositories/exerciseMappers";
import { dayToRow, programExerciseToRow, programToRow } from "../lib/repositories/programMappers";

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "'{}'";
    return `ARRAY[${value.map((item) => sqlLiteral(item)).join(", ")}]::text[]`;
  }
  // String: escape single quotes by doubling them, the standard SQL way.
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatement(table: string, rows: Record<string, unknown>[], conflictTarget = "id"): string {
  if (rows.length === 0) return `-- (no ${table} rows)`;
  const columns = Object.keys(rows[0] as Record<string, unknown>);
  // Double-quoted throughout: "order" is a reserved word and would otherwise
  // produce a syntax error in an unquoted column list.
  const quotedColumns = columns.map((column) => `"${column}"`).join(", ");
  const values = rows
    .map((row) => `  (${columns.map((column) => sqlLiteral(row[column])).join(", ")})`)
    .join(",\n");
  return `insert into public.${table} (${quotedColumns}) values\n${values}\non conflict (${conflictTarget}) do nothing;`;
}

const exerciseRows = SEED_EXERCISES.map(exerciseToRow);
const substitutionRows = SEED_EXERCISES.flatMap((exercise) =>
  (exercise.substitutionExerciseIds ?? []).map((substituteExerciseId) => ({
    exercise_id: exercise.id as string,
    substitute_exercise_id: substituteExerciseId as string,
  })),
);
const programRows = SEED_PROGRAMS.map(programToRow);
const sessionRows = SEED_WORKOUT_DAYS.map(dayToRow);
const programExerciseRows = SEED_PROGRAM_EXERCISES.map(programExerciseToRow);

const sql = `-- Generated by scripts/generateSeedSql.ts — do not edit by hand.
-- Regenerate with: npx tsx scripts/generateSeedSql.ts (from apps/mobile)
--
-- Loads the built-in exercise library and programme catalogue. Runs
-- automatically on \`supabase db reset\` / first \`supabase start\`, or apply
-- it to a remote project with:
--   psql "$SUPABASE_DB_URL" -f supabase/seed.sql

${insertStatement("exercises", exerciseRows as unknown as Record<string, unknown>[])}

${insertStatement("exercise_substitutions", substitutionRows, "exercise_id, substitute_exercise_id")}

${insertStatement("programs", programRows as unknown as Record<string, unknown>[])}

${insertStatement("program_sessions", sessionRows as unknown as Record<string, unknown>[])}

${insertStatement("program_exercises", programExerciseRows as unknown as Record<string, unknown>[])}
`;

const outPath = resolve(__dirname, "../../../supabase/seed.sql");
writeFileSync(outPath, sql, "utf8");

console.log(
  `Wrote ${outPath}\n` +
    `  ${exerciseRows.length} exercises, ${substitutionRows.length} substitutions, ` +
    `${programRows.length} programmes, ${sessionRows.length} sessions, ${programExerciseRows.length} programme exercises.`,
);
